### ISSUE TITLE
AddScreen Interaction Bug

### ISSUE THREAD

**Issue by Schdegga** [spsbstn/ProjectWatchlist#2]
When you type and enter something in AddScreen, while it is still in Animation, AddScreen doesn´t hide afterwards. The show however is added properly.

**Comment by spsbstn** [comment]
Fixed in Commit [b8bffbfd0a](https://github.com/Embisto/ProjectWatchlist/commit/b8bffbfd0a925cd607adab09ca9518020d94ae9c)
