### ISSUE TITLE
Limit User-Input-Length

### ISSUE THREAD

**Issue by Schdegga** [spsbstn/ProjectWatchlist#24]
Series with too long names mess up layout

**Comment by spsbstn** [comment]
Need an example. Even "aqua teen something you know whatever" works like a charm for me ;P

**Comment by Schdegga** [comment]
hhhhadfgkosakdfokasdopgjaesijrgilkasjdgijöadsifjgfsdjigjsfdöoigjfsdjgispfdjgasjd

for example :D 
Not likely, but still, shouldn´t be possible

**Comment by spsbstn** [comment]
Very unlikely :D But a simple 

``` javascript
wrapMode: Text.WrapAnywhere
```

should do it

**Comment by spsbstn** [comment]
Fixed with last Commit
