### ISSUE TITLE
Inform user if loading of .db file went wrong

### ISSUE THREAD

**Issue by Schdegga** [spsbstn/ProjectWatchlist#25]
Our Beta-Tester corrupted the databasefile in Editor  -> shows were no longer loaded, but no new .db file was created

**Comment by spsbstn** [comment]
What does corrupted the databasefile in Editor mean?  A simple texteditor ?

**Comment by Schdegga** [comment]
Yes, simple texteditor

**Comment by spsbstn** [comment]
It's a sql file. You can't use a texteditor. Besides: delete the corrupted one and everything's fine:D
But i cant see why we should deal with this issue. If someone changes app Files it's his own fault. And btw that's the reason why we should use .appData to store files :D

**Comment by spsbstn** [comment]
added ErrorDialog
