### ISSUE TITLE
Add timeout if connection to onlineDatabase is not possible and add ErrorMessage

### ISSUE THREAD

**Issue by spsbstn** [spsbstn/ProjectWatchlist#68]

**Comment by Schdegga** [comment]
Fixed in e4c628cc078d139af704409e330fbc9718852f56?

**Comment by spsbstn** [comment]
Dear @Schdegga,

![Image of Yaktocat](http://www.snugglyoranges.com/wp-content/uploads/2014/03/happy-3.gif)

I therefore declare this isssue closed.
